### PR TITLE
Patient categories in db schema

### PR DESCRIPTION
**Pull request by sylvr3**

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
`targetCount` is good. :+1:
The other three will need to be calculated on the fly.
I'm not sure they should be stored in the DB.
Thoughts @poojaRal ?

**Comment by sylvr3** [comment]
@ChristianMurphy Is there a list of JSLint guidelines online so I can easily check my code for JSLint errors before pushing?

**Comment by ChristianMurphy** [comment]
`gulp lint`
Or if you would like IDE support for ESLint can integrate with most editors.
http://eslint.org/docs/user-guide/integrations

**Comment by sylvr3** [comment]
Okay, I am having issues fixing these minor JSLint errors. Maybe the text editor I am using is messing up the formatting of my source code? I am using Sublime Text. What are you using?

**Comment by ChristianMurphy** [comment]
The editor does not seem to be causing the issue, but it also is not automatically helping either.
I use [Atom Editor](https://atom.io/) with [EditorConfig](https://atom.io/packages/editorconfig), [Linter](https://atom.io/packages/linter) and [Linter Eslint](https://atom.io/packages/linter-eslint) to help with code style.

**Comment by ChristianMurphy** [comment]
And if you do choose to go with Atom.
[Monokai](https://atom.io/themes/monokai), [Minimap](https://atom.io/packages/minimap) and [File Icons](https://atom.io/packages/file-icons) can make Atom look and feel more like sublime text.

**Comment by poojaRal** [comment]
The target count for each trial would be manually entered by the clinician or the admin while adding each trial into the system. The other 3 counts should be calculative.

**Comment by sylvr3** [comment]
Is that all that needs to be added to the schema? Is this good to go?

**Comment by ChristianMurphy** [comment]
Database table LGTM.
What is `globule` library being used for?

**Comment by sylvr3** [comment]
I had to install globule in order to get lint to work properly.

**Comment by ChristianMurphy** [comment]
Delete the `node_modules` folder.
Run `npm install` again and linter will work as is.
Please remove the top level dependency on `globule`.

**Comment by sylvr3** [comment]
The globule dependency is removed, but git won't add/commit those changes. You might need to remove that dependency manually.

**Comment by ChristianMurphy** [comment]
LGTM

**Pull request merged**
