### PR TITLE
Survey view

### PR DESCRIPTION
**Pull request by beccannlittle**
The table scrolls.
screen shot 2015-11-15 at 7 20 34 pm
screen shot 2015-11-15 at 7 20 42 pm

### CODE REVIEW

**Comment by beccannlittle** [comment]
@poojaRal seed SQL script didn't include an example of a survey instance

@ChristianMurphy I know you explained how the join works, but I still don't get it :hankey: let's work on hooking it up during this week.

**Comment by poojaRal** [comment]
Yup I didn't include a survey instance because I am currently working on
the APIs.

I have updated the seed script with all the other tables data.
Please check latest version.

**Comment by beccannlittle** [comment]
@poojaRal so basically we still don't have survey instance data?

**Comment by ChristianMurphy** [comment]
@beccannlittle for this page to display what you are currently showing, it's going to take a plain old SQL query.
http://docs.sequelizejs.com/en/latest/docs/raw-queries/
I'll take a more in depth look at how to write the query tomorrow.

**Comment by poojaRal** [comment]
I have a query which I created for testing purpose.

Let me just post it here.

INSERT INTO survey_instance VALUES (1,'2015-11-15 09:00:00','2016-02-15
09:00:00',NULL,NULL,false,'2015-11-15 09:00:00','2015-11-15
09:00:00',NULL,1,1 );

For this to work,  under the first trial, you need to create a patient and
then run this query in mysql.

**Comment by ChristianMurphy** [comment]
@beccannlittle Wrote up a query that *should* get all the information needed.
Currently it is returning an empty array, it will need `survey_instance`, `survey_template`, `question_instance`, `question_template` and `question_option` data to work as expected.

cc @poojaRal

**Comment by poojaRal** [comment]
Yup.. Looks like all the required data is present.

**Comment by beccannlittle** [comment]
Fixed #115

**Pull request merged**
