### PR TITLE
Add patient categories to trial table

### PR DESCRIPTION
**Pull request by sylvr3**
I added the following categories to the trial table on the Dashboard: Target Number of Patients, 	Recruited Number of Patients, Active, Completed, and # Compliant, in addition to the categories we already had in the table.
I also added those categories to the presenter (trial.js).
The data for those fields is currently empty and needs to be added to the database schema (which is a separate task).
Can you take a look and let me know if the UI looks good and we can push this? @beccannlittle

### CODE REVIEW

**Comment by beccannlittle** [comment]
See [screenshots].(https://docs.google.com/a/asu.edu/document/d/1EuDGVcsHDmKNoZR7HXJKUVT0jh2v5s9lBf71qLG9px0/edit?usp=sharing)

- Status column is now a dropdown button. 
- Patient categories are consolidated into three columns rather than six in an attempt to reduce confusion
- Removed duration column

@sylvr3 @ChristianMurphy thoughts?

**Comment by sylvr3** [comment]
I think it looks much more cleaner and easier to understand this way, but I agree with you about the compliant/noncompliant counts not being emphasized.

**Comment by ChristianMurphy** [comment]
@beccannlittle 
Looks good,
IMO compliance emphasis is fine.
For mobile is there a nice looking alternative to the tall vertical content?

**Comment by beccannlittle** [comment]
@ChristianMurphy we could hide the second row on mobile, but that's not a great solution. We lose the percentage breakdowns. Text within the progress bars themselves (labels) is [supported in BS v3](http://getbootstrap.com/components/#progress) but [not in BS v4](http://v4-alpha.getbootstrap.com/components/progress/).

**Comment by beccannlittle** [comment]
I'm open to another way to display the categories, but we have to choose between many columns or tall rows.

**Comment by ChristianMurphy** [comment]
It should be fine as is then :smile: 
:+1:

**Pull request merged**
