### PR TITLE
Charts

### PR DESCRIPTION
**Pull request by ChristianMurphy**
**Commit Overview**
* Adds example `Chart.js` charts
* Make views responsive on mobile screen

### CODE REVIEW

**Comment by sylvr3** [comment]
LGTM!

**Comment by ChristianMurphy** [comment]
dashboard
trial

**Comment by sylvr3** [comment]
I don't see the second chart showing each Trial. @ChristianMurphy

**Comment by ChristianMurphy** [comment]
@sylvr3 
Can you check the developer console in the browser, switch to the console tab in the developer console, refresh the page and see if any errors are listed?

**Comment by ChristianMurphy** [comment]
@sylvr3 also be aware that the application is now trying to pull actual trial data from the database.

Running `gulp sync`
and running some curl commands
``` sh
curl -X POST -H "Content-Type: application/json" -d '{"name": "Trial 1", "description":"first trial", "startAt": "10-21-2012", "endAt": "12-21-2012", "IRBID": "test1"}' localhost:3000/trial
curl -X POST -H "Content-Type: application/json" -d '{"name": "Trial 2", "description":"second trial", "startAt": "11-21-2012", "endAt": "12-21-2012", "IRBID": "test2"}' localhost:3000/trial
curl -X POST -H "Content-Type: application/json" -d '{"name": "Trial 3", "description":"third trial", "startAt": "12-01-2012", "endAt": "12-21-2012", "IRBID": "test3"}' localhost:3000/trial
```

should add some data into the database and ensure everything is running smoothly

**Comment by sylvr3** [comment]
@ChristianMurphy Thanks for the curl commands. That's what I was missing! Everything is running smoothly now.

**Pull request merged**
