### PR TITLE
[RFC] New Table Format

### PR DESCRIPTION
**Pull request by ChristianMurphy**
This PR purposes a unified way for presenting information in tables.

### Overall Format
| Context   | Action   | Dynamic Data   | Static Data |
| ----------|----------|----------------|-------------|

**Context** Let the clinician know what they are looking at.
E.G. the name of a trial, the pin of a patient. This should display information that is human understandable, rather than implementation specific (such as id).

**Action** Let the clinician know what they can do, this would be a link or a button.

**Dynamic Data** Information that will be changing over time.
E.G. Whether a patient is compliant or what stage that patient is in.

**Static Data** Information that will stay the same throughout.
E.G. Trial Start Date, End Date and Duration.

### Format for Dashboard
| Context   | Action   | Dynamic Data                           | Static Data                    |
| ----------|----------|----------------------------------------|--------------------------------|
| Name      | View     | Status, # Noncompliant, Total Patients | Duration, Start Date, End Date |

**Name** Name of the Trial
**View** A link to view trial details
**Status** What stage the Trial is in
* Pending - Waiting for admin approval
* Upcoming - Trial has not started yet
* In Progress - Trial is currently running
* Completed - Trial is over

**# Noncompliant** Number of patients how have crossed the noncompliant threshold
**Total Patients** Number of patients in the trial overall
**Duration** Length of trial relative to start and end date
**Start Date** The day the trial starts
**End Date** The day the trial ends

### Screenshot
dashboardscreenshot

Any thoughts? @beccannlittle @sylvr3 @poojaRal

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
### Format for Trial Dashboard Table
| Context          | Action   | Dynamic Data                                                                      | Static Data |
| -----------------|----------|-----------------------------------------------------------------------------------|-------------|
| Patient Pin      | View     | Status, Stage, Survey Type, Last Taken, Consecutive Missed, Total Missed Patients |             |

**Patient Pin** Four digit number representing a patient record.

**Status** How well the patient is going in the trial

* Compliant - Patient is above the threshold
* Semicompliant - Patient is near or on the threshold
* Noncompliant - Patient is below the threshold

**Stage** Controls how many and what types of surveys are given.

**Survey Type**  How frequently surveys are given
*Duplicate of Stage?*

**Last Taken** Date that last survey was taken
*Would a duration since last taken make work sense?*

**Consecutive Missed** How many surveys in a row patient has missed.
*Should this be replaced by the positive version* **Consecutive Taken**? 

**Total Missed** Number of surveys patient has missed overall in this trial

### Screenshot
trialscreenshot

**Comment by poojaRal** [comment]
This looks fantastic

**Comment by beccannlittle** [comment]
I'm a big fan.

**Comment by sylvr3** [comment]
I think this a great way to organize the table. Looks good!

**Comment by ChristianMurphy** [comment]
@beccannlittle 
for desktop (lg and xl) I'm on the fence. The empty space seems to be enough to separate columns, adding the vertical part seems unnecessary.
For mobile/tablet I'm leaning yes, there it seems much more useful, when there isn't the empty space separating.

What are your thoughts?

tablebordered
smtablebordered

**Comment by beccannlittle** [comment]
@ChristianMurphy I was referring to dividers ONLY between the different sections - context, action, dynamic-, and static data.

**Comment by ChristianMurphy** [comment]
@beccannlittle probably not

1. it would require custom css
2. we would need to explain to clinicians why these sections are different to give them the *possibility* of being more efficient

**Comment by ChristianMurphy** [comment]
Added messages when the there are no Trials and when there are no Patients
addpatients
addtrial

**Comment by sylvr3** [comment]
Is the Actual Submission Time column necessary for the patient surveys page? I know it is defined in the schema, but what is the purpose of that column? It seems redundant (we are already tracking the user submission time).

actualsubmissiontime

**Comment by ChristianMurphy** [comment]
@sylvr3 your right it probably should not be separated in this view.

@poojaRal could you remind me why there is a separate User and Actual submitted time in the DB?

**Comment by poojaRal** [comment]
Hi,

In the portal currently there is a provision that user hit the submit
button in the app, but the survey didn't get submitted due to connectivity
issues or some server issues.

Hence user_submission_time is the time when user hit the submit button.
Actual_submission_time is the time when the answers got saved in the
database.

**Pull request merged**
