### PR TITLE
[RFC] Stage and EventListener tables

### PR DESCRIPTION
**Pull request by ChristianMurphy**
**Commit Overview**
* Adds new Stage and EventListener tables
* Manually close database connection after sync

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
stage and events

Where each Patient belongs to a Trial, and for the Trial each Patient is in a single stage.
Each Stage is a collection of Event Listeners, and Event Listeners are rules that listen for certain conditions, and can either set Compliance or Generate a Survey Instance.
The Event Listers/Rules would be run both on a Timer (a cron job) and whenever a Patient updates a Survey Instance.
Event Listeners would evaluate only a Single Patient at a time.

Any Thoughts @poojaRal ?

Should Event Listeners be single use or reusable per across Stages?
Can a Patient be in multiple Stages?

**Comment by poojaRal** [comment]
Hey,

I will just form a good explanation to this and get back to you in sometime.

**Comment by poojaRal** [comment]
Hello Christian,

Yes, your explanation is correct. Each patient belongs to  a single trial.
When he is active in a trial, he will be associated with a particular stage
from that trial.
Each stage is a collection of event listeners and event listeners will
either set compliance or generate a survey instance for a patient based on
certain rules and conditions.

Yes, event listeners would evaluate only a single patient at a time based
on a particular event.
A patient can be present in a single stage at a given time.
Hope this made sense :)

Thanks,
Pooja

On Tue, Oct 27, 2015 at 10:22 AM, Christian Murphy <notifications@github.com

**Comment by ChristianMurphy** [comment]
Sounds good, Thanks @poojaRal

**Pull request merged**
