### PR TITLE
Pin as Unique Key

### PR DESCRIPTION
**Pull request by ChristianMurphy**
**Commit Overview**
* Sets `pin` as Patient's Primary Key
* Renames `startAt` and `endAt` to `IRBStart` and `IRBEnd` respectively
* Adds JSDoc for Trial model
* Patient route is now based off `pin`

Thoughts @poojaRal ?

### CODE REVIEW

**Comment by poojaRal** [comment]
Looks good to me.
We can keep pin and patient_ id  both as primary keys right? Wouldn't this
be better?

*Commit Overview*

   - Sets pin as Patient's Primary Key
   - Renames startAt and endAt to IRBStart and IRBEnd respectively
   - Adds JSDoc for Trial model
   - Patient route is now based off pin

Thoughts @poojaRal <https://github.com/poojaRal> ?
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/ser515asu/PRP-Manhattan-Project/pull/63
Commit Summary

   - update pin to be primary key for patient

File Changes

   - *M* model/patient.js
   <https://github.com/ser515asu/PRP-Manhattan-Project/pull/63/files#diff-0>
   (3)
   - *M* model/trial.js
   <https://github.com/ser515asu/PRP-Manhattan-Project/pull/63/files#diff-1>
   (15)
   - *M* presenter/create-patient.js
   <https://github.com/ser515asu/PRP-Manhattan-Project/pull/63/files#diff-2>
   (49)
   - *M* presenter/dashboard.js
   <https://github.com/ser515asu/PRP-Manhattan-Project/pull/63/files#diff-3>
   (4)
   - *M* router.js
   <https://github.com/ser515asu/PRP-Manhattan-Project/pull/63/files#diff-4>
   (8)
   - *M* view/partial/add-trial.hbs
   <https://github.com/ser515asu/PRP-Manhattan-Project/pull/63/files#diff-5>
   (4)

Patch Links:

   - https://github.com/ser515asu/PRP-Manhattan-Project/pull/63.patch
   - https://github.com/ser515asu/PRP-Manhattan-Project/pull/63.diff

—
Reply to this email directly or view it on GitHub
<https://github.com/ser515asu/PRP-Manhattan-Project/pull/63>.

**Comment by ChristianMurphy** [comment]
sure, I updated to id primary key, and pin being a unique Integer.
IMO we should avoid multiple primary keys,
This is what the table currently looks like.
```
+---------------+---------------------------------+------+-----+---------+----------------+
| Field         | Type                            | Null | Key | Default | Extra          |
+---------------+---------------------------------+------+-----+---------+----------------+
| id            | int(11)                         | NO   | PRI | NULL    | auto_increment |
| pin           | int(11)                         | NO   | UNI | NULL    |                |
| deviceType    | enum('android','ios','windows') | YES  |     | NULL    |                |
| deviceVersion | varchar(255)                    | YES  |     | NULL    |                |
| dateStarted   | datetime                        | YES  |     | NULL    |                |
| dateCompleted | datetime                        | YES  |     | NULL    |                |
| createdAt     | datetime                        | NO   |     | NULL    |                |
| updatedAt     | datetime                        | NO   |     | NULL    |                |
| deletedAt     | datetime                        | YES  |     | NULL    |                |
| trialId       | int(11)                         | YES  | MUL | NULL    |                |
| stageId       | int(11)                         | YES  | MUL | NULL    |                |
+---------------+---------------------------------+------+-----+---------+----------------+
```

**Comment by poojaRal** [comment]
Yup.. This looks good

**Comment by ChristianMurphy** [comment]
@poojaRal @sylvr3 @beccannlittle 
This change will require a DB reset after it is merged.

**Pull request merged**
