### PR TITLE
Update Documentation and Dependencies

### PR DESCRIPTION
**Pull request by ChristianMurphy**
* update installation instructions
* update eslint
* rename .eslintrc to .eslintrc.yml
* update other dependencies

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@sylvr3 Installing [node gyp](https://github.com/nodejs/node-gyp#installation) should resolve the issues you are having with bcrypt not installing.

**Comment by sylvr3** [comment]
I installed node gyp (using the command in the link above) and it still can't find the module bcrypt.

**Comment by ChristianMurphy** [comment]
After installing `node-gyp` run `npm install` again.

**Comment by sylvr3** [comment]
Here are the error messages I get when I do npm install after I install node gyp:

gulp issue

**Comment by ChristianMurphy** [comment]
hmm a couple things.
First try running `nvm use 4` because this code will not work on node `0.12.x`.
Once on version 4 try running `npm install` again.

If there is still an error, try `npm install --global npm`.
Then run `npm install` again.

**Comment by sylvr3** [comment]
screenshot from 2015-11-21 10 52 32

**Comment by ChristianMurphy** [comment]
0a2139c2-903e-11e5-993d-5b06f8438e66

Follow all of the instructions to install [node-gyp](https://github.com/nodejs/node-gyp#installation)

On linux it requires `python 2.7`, `gcc` and `g++`.

**Comment by sylvr3** [comment]
:+1:

**Pull request merged**
