### PR TITLE
Bootstrap Calendar

### PR DESCRIPTION
**Pull request by ChristianMurphy**
alternative to FullCalendar

### CODE REVIEW

**Comment by sylvr3** [comment]
Is the calendar appearing on the patient page on your end? I don't see it on mine.

**Comment by ChristianMurphy** [comment]
calendar

**Comment by sylvr3** [comment]
Hmmm...maybe I'm not running the gulp commands in the correct order.
I am doing the nvm use v4 command, then gulp sync, then entering the curl commands, then gulp start.
Is that the correct sequence of commands?

**Comment by sylvr3** [comment]
Finally got it to display! :+1: :grinning:

**Comment by ChristianMurphy** [comment]
Closing in favor of #37

**Pull request closed without merging**
